'use client';
import AppShell from './AppShell';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Plus, Trash2, Pencil, Search, ArrowLeft, Save, X } from 'lucide-react';

type Project={id:string;name:string};
type Field={key:string;label:string;type?:string;required?:boolean;options?:string[];placeholder?:string;step?:string};
type Config={table:string;title:string;subtitle:string;singular:string;fields:Field[];columns:{key:string;label:string}[]};

const configs:Record<string,Config>={
 scenes:{table:'scenes',title:'Scenes',subtitle:'Script breakdown for this production.',singular:'scene',fields:[
  {key:'scene_number',label:'Scene number',required:true},{key:'int_ext',label:'INT / EXT',options:['INT','EXT','INT/EXT']},{key:'day_night',label:'Time',options:['DAY','NIGHT','DAWN','DUSK']},{key:'location',label:'Location'},{key:'set_name',label:'Set / set name'},{key:'description',label:'Description',type:'textarea'},{key:'characters',label:'Characters',type:'textarea'},{key:'extras',label:'Extras',type:'textarea'},{key:'props',label:'Props',type:'textarea'},{key:'wardrobe',label:'Wardrobe',type:'textarea'},{key:'makeup',label:'Makeup / hair',type:'textarea'},{key:'vehicles',label:'Vehicles',type:'textarea'},{key:'special_equipment',label:'Special equipment',type:'textarea'},{key:'notes',label:'Notes',type:'textarea'}],columns:[{key:'scene_number',label:'Scene'},{key:'int_ext',label:'INT/EXT'},{key:'day_night',label:'Time'},{key:'location',label:'Location'},{key:'characters',label:'Cast'}]},
 crew:{table:'crew',title:'Crew',subtitle:'Cast and crew roster with rates and contact details.',singular:'crew member',fields:[{key:'name',label:'Name',required:true},{key:'department',label:'Department'},{key:'position',label:'Position'},{key:'phone',label:'Phone'},{key:'email',label:'Email',type:'email'},{key:'day_rate',label:'Day rate (RSD)',type:'number',step:'0.01'},{key:'availability',label:'Availability',options:['Available','Hold','Unavailable']},{key:'notes',label:'Notes',type:'textarea'}],columns:[{key:'name',label:'Name'},{key:'department',label:'Department'},{key:'position',label:'Position'},{key:'phone',label:'Phone'},{key:'day_rate',label:'Day rate'}]},
 locations:{table:'locations',title:'Locations',subtitle:'Scouting, rates, permits and practical production notes.',singular:'location',fields:[{key:'name',label:'Location name',required:true},{key:'address',label:'Address'},{key:'contact_name',label:'Contact person'},{key:'phone',label:'Phone'},{key:'price',label:'Rate (RSD)',type:'number',step:'0.01'},{key:'permits',label:'Permits',type:'textarea'},{key:'parking',label:'Parking',type:'textarea'},{key:'electricity',label:'Electricity',type:'textarea'},{key:'dressing_room',label:'Dressing room',type:'textarea'},{key:'catering',label:'Catering',type:'textarea'},{key:'notes',label:'Notes',type:'textarea'}],columns:[{key:'name',label:'Location'},{key:'address',label:'Address'},{key:'contact_name',label:'Contact'},{key:'price',label:'Rate'}]},
 schedule:{table:'shooting_schedule',title:'Shooting Schedule',subtitle:'Build shooting days from your scenes and locations.',singular:'schedule item',fields:[{key:'shoot_day',label:'Shoot day',type:'number',required:true},{key:'shoot_date',label:'Date',type:'date'},{key:'scene_id',label:'Scene',type:'scene'},{key:'start_time',label:'Start',type:'time'},{key:'end_time',label:'End',type:'time'},{key:'location',label:'Location'},{key:'crew_call',label:'Crew call',type:'time'},{key:'lunch_minutes',label:'Lunch (min)',type:'number'},{key:'notes',label:'Notes',type:'textarea'}],columns:[{key:'shoot_day',label:'Day'},{key:'shoot_date',label:'Date'},{key:'scene_id',label:'Scene'},{key:'start_time',label:'Start'},{key:'end_time',label:'End'},{key:'location',label:'Location'}]},
 reports:{table:'daily_reports',title:'Daily Reports',subtitle:'Record what actually happened on each shooting day.',singular:'daily report',fields:[{key:'shoot_day',label:'Shoot day',type:'number',required:true},{key:'report_date',label:'Date',type:'date'},{key:'crew_call',label:'Crew call',type:'time'},{key:'first_shot',label:'First shot',type:'time'},{key:'lunch_time',label:'Lunch',type:'time'},{key:'wrap_time',label:'Wrap',type:'time'},{key:'scenes_scheduled',label:'Scenes scheduled',type:'textarea'},{key:'scenes_completed',label:'Scenes completed',type:'textarea'},{key:'scenes_omitted',label:'Scenes omitted',type:'textarea'},{key:'overtime_minutes',label:'Overtime (min)',type:'number'},{key:'delays',label:'Delays',type:'textarea'},{key:'incidents',label:'Incidents',type:'textarea'},{key:'additional_expenses',label:'Additional expenses (RSD)',type:'number',step:'0.01'},{key:'notes',label:'Notes',type:'textarea'}],columns:[{key:'shoot_day',label:'Day'},{key:'report_date',label:'Date'},{key:'scenes_completed',label:'Scenes completed'},{key:'overtime_minutes',label:'OT min'},{key:'additional_expenses',label:'Extra spend'}]},
 calls:{table:'call_sheets',title:'Call Sheets',subtitle:'Production calls, weather, catering and emergency information.',singular:'call sheet',fields:[{key:'shoot_day',label:'Shoot day',type:'number',required:true},{key:'call_date',label:'Date',type:'date'},{key:'general_call',label:'General call',type:'time'},{key:'weather',label:'Weather',type:'textarea'},{key:'parking',label:'Parking',type:'textarea'},{key:'catering',label:'Catering',type:'textarea'},{key:'emergency_contacts',label:'Emergency contacts',type:'textarea'},{key:'notes',label:'Notes',type:'textarea'}],columns:[{key:'shoot_day',label:'Day'},{key:'call_date',label:'Date'},{key:'general_call',label:'General call'},{key:'weather',label:'Weather'},{key:'catering',label:'Catering'}]},
};

function fmt(v:any){if(v===null||v===undefined||v==='')return '—'; if(typeof v==='number')return v.toLocaleString('en-US'); return String(v);}

const money_keys=new Set(['day_rate','price','additional_expenses']);

export default function ProjectModule({kind}:{kind:keyof typeof configs}){
 const cfg=configs[kind]; const [projects,setProjects]=useState<Project[]>([]); const [projectId,setProjectId]=useState(''); const [rows,setRows]=useState<any[]>([]); const [scenes,setScenes]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [search,setSearch]=useState(''); const [editing,setEditing]=useState<any|null>(null); const [form,setForm]=useState<Record<string,any>>({});
 const sb=createClient();
 useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user){location.href='/login';return;} const {data,error}=await sb.from('projects').select('id,name').order('created_at',{ascending:false});if(error)setError(error.message); else {setProjects(data||[]); const qp=new URLSearchParams(location.search).get('project'); const chosen=qp&&data?.some(p=>p.id===qp)?qp:(data?.[0]?.id||''); setProjectId(chosen);} setLoading(false);})();},[]);
 useEffect(()=>{if(!projectId)return; loadRows(); if(kind==='schedule')loadScenes();},[projectId,kind]);
 async function loadRows(){setLoading(true); const {data,error}=await sb.from(cfg.table).select('*').eq('project_id',projectId).order('created_at',{ascending:false}); if(error)setError(error.message);else setRows(data||[]);setLoading(false);}
 async function loadScenes(){const {data}=await sb.from('scenes').select('id,scene_number,description,location').eq('project_id',projectId).order('scene_number');setScenes(data||[]);}
 function openNew(){const o:any={};cfg.fields.forEach(f=>o[f.key]=f.type==='number'?'': '');setForm(o);setEditing({new:true});setError('');}
 function openEdit(r:any){const o:any={};cfg.fields.forEach(f=>o[f.key]=r[f.key]??'');setForm(o);setEditing(r);setError('');}
 async function save(){setSaving(true);setError('');const payload:any={...form,project_id:projectId}; for(const f of cfg.fields){if(f.type==='number'&&payload[f.key]!=='')payload[f.key]=Number(String(payload[f.key]).replace(/\./g,'').replace(',','.'));if(payload[f.key]==='')payload[f.key]=null;} let result=editing?.new?await sb.from(cfg.table).insert(payload).select().single():await sb.from(cfg.table).update(payload).eq('id',editing.id).eq('project_id',projectId).select().single(); if(result.error)setError(result.error.message);else{setEditing(null);await loadRows();}setSaving(false);}
 async function remove(id:string){if(!confirm(`Delete this ${cfg.singular}?`))return;const {error}=await sb.from(cfg.table).delete().eq('id',id).eq('project_id',projectId);if(error)setError(error.message);else loadRows();}
 const project=projects.find(p=>p.id===projectId); const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())),[rows,search]);
 if(loading&&!projects.length)return <AppShell><div className="empty"><h3>Loading production workspace…</h3></div></AppShell>;
 return <AppShell><div className="top"><div><div className="eyebrow">{project?.name||'PROJECT'} · PRODUCTION</div><h1 className="title">{cfg.title}</h1><div className="subtitle">{cfg.subtitle}</div></div><div className="actions"><Link className="btn" href={projectId?`/projects/${projectId}`:'/projects'}><ArrowLeft size={13}/> Project</Link><select className="select" value={projectId} onChange={e=>{setProjectId(e.target.value);history.replaceState(null,'',`/${kind==='calls'?'call-sheets':kind}?project=${e.target.value}`)}}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button className="btn primary" onClick={openNew}><Plus size={14}/> Add {cfg.singular}</button></div></div>
 {error&&<div className="error" style={{marginBottom:12}}>{error}</div>}
 <section className="card"><div className="section-head"><div><div className="eyebrow">{rows.length} records</div><h2>{cfg.title} library</h2></div><div className="search"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${cfg.title.toLowerCase()}...`}/></div></div>{loading?<div className="empty">Loading…</div>:filtered.length===0?<div className="empty"><h3>No {cfg.title.toLowerCase()} yet</h3><div className="subtitle">Add the first record to start building this production module.</div><button className="btn primary" style={{marginTop:14}} onClick={openNew}><Plus size={14}/> Add {cfg.singular}</button></div>:<div className="table-wrap"><table className="table"><thead><tr>{cfg.columns.map(c=><th key={c.key}>{c.label}</th>)}<th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{cfg.columns.map(c=><td key={c.key}>{c.key==='scene_id'?fmt(scenes.find(s=>s.id===r[c.key])?.scene_number||r[c.key]):fmt(r[c.key])}</td>)}<td><div style={{display:'flex',gap:6}}><button className="btn ghost" onClick={()=>openEdit(r)} title="Edit"><Pencil size={13}/></button><button className="btn ghost" onClick={()=>remove(r.id)} title="Delete"><Trash2 size={13}/></button></div></td></tr>)}</tbody></table></div>}</section>
 {editing&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><div className="eyebrow">{editing.new?'NEW':'EDIT'} · {cfg.singular.toUpperCase()}</div><h2>{editing.new?'Add':'Edit'} {cfg.singular}</h2></div><button className="btn ghost" onClick={()=>setEditing(null)}><X size={16}/></button></div><div className="form-grid">{cfg.fields.map(f=><label key={f.key} className={f.type==='textarea'?'full':''}>{f.label}{f.required&&' *'}{f.type==='textarea'?<textarea value={form[f.key]??''} placeholder={f.placeholder} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:f.options?<select value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">Select…</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='scene'?<select value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">Select scene…</option>{scenes.map(s=><option value={s.id} key={s.id}>Scene {s.scene_number} · {s.location||'No location'}</option>)}</select>:<input
 type={money_keys.has(f.key)?'text':(f.type||'text')}
 inputMode={money_keys.has(f.key)?'decimal':undefined}
 step={money_keys.has(f.key)?undefined:f.step}
 value={form[f.key]??''}
 placeholder={f.placeholder}
 onChange={e=>setForm({...form,[f.key]:e.target.value})}
 />}</label>)}</div><div className="modal-actions"><button className="btn" onClick={()=>setEditing(null)}>Cancel</button><button className="btn primary" disabled={saving} onClick={save}><Save size={14}/>{saving?'Saving…':'Save'}</button></div></div></div>}
 </AppShell>
}
