'use client';
import AppShell from '@/components/AppShell';
import Link from 'next/link';
import {CalendarDays, Users, MapPin, WalletCards, FileText, Clapperboard, ClipboardCheck, Files, ArrowUpRight} from 'lucide-react';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';

type Project={id:string;name:string;project_type:string;producer:string|null;director:string|null;status:string;budget:number|string;start_date:string|null;end_date:string|null};

export default function Project(){
 const {id}=useParams<{id:string}>(); const [project,setProject]=useState<Project|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{const sb=createClient(); const {data,error}=await sb.from('projects').select('id,name,project_type,producer,director,status,budget,start_date,end_date').eq('id',id).single(); if(error)setError(error.message); else setProject(data as Project); setLoading(false);})();},[id]);
 if(loading)return <AppShell><div className="empty"><h3>Loading project…</h3><div className="subtitle">Opening the production workspace.</div></div></AppShell>;
 if(error||!project)return <AppShell><div className="empty"><h3>Project not found</h3><div className="subtitle">{error||'You may not have access to this project.'}</div><Link href="/projects" className="btn" style={{marginTop:14}}>← Back to projects</Link></div></AppShell>;
 const money=Number(project.budget||0).toLocaleString('en-US',{maximumFractionDigits:0});
 const modules=[['Scenes','Script breakdown',`/scenes?project=${project.id}`,Clapperboard],['Schedule','Shooting days',`/schedule?project=${project.id}`,CalendarDays],['Call Sheets','Production calls',`/call-sheets?project=${project.id}`,FileText],['Crew','Cast & crew',`/crew?project=${project.id}`,Users],['Locations','Scouting & bookings',`/locations?project=${project.id}`,MapPin],['Budget','Costs & expenses',`/budget?project=${project.id}`,WalletCards],['Daily Reports','Production reports',`/reports?project=${project.id}`,ClipboardCheck],['Documents','Files & paperwork',`/documents?project=${project.id}`,Files]] as const;
 return <AppShell><div className="top"><div><div className="eyebrow">{project.project_type.toUpperCase()} · {project.status.toUpperCase()}</div><h1 className="title">{project.name}</h1><div className="subtitle">{project.producer?`Producer ${project.producer}`:'Producer not assigned'}{project.director?` · Director ${project.director}`:''}</div></div><div className="actions"><Link href="/projects" className="btn">← Projects</Link><button className="btn primary">Project settings</button></div></div><div className="grid stats"><div className="card"><div className="statlabel">STATUS</div><div className="statvalue" style={{fontSize:22}}>{project.status}</div><div className="statmeta">Current production stage</div></div><div className="card"><div className="statlabel">BUDGET</div><div className="statvalue">€{money}</div><div className="statmeta">Planned production budget</div></div><div className="card"><div className="statlabel">START DATE</div><div className="statvalue" style={{fontSize:22}}>{project.start_date?new Date(project.start_date).toLocaleDateString('en-GB'):'—'}</div><div className="statmeta">Production start</div></div><div className="card"><div className="statlabel">END DATE</div><div className="statvalue" style={{fontSize:22}}>{project.end_date?new Date(project.end_date).toLocaleDateString('en-GB'):'—'}</div><div className="statmeta">Production end</div></div></div><div className="grid four" style={{marginTop:13}}>{modules.map(([label,meta,href,Icon])=><Link href={href} key={label} className="card" style={{textDecoration:'none',color:'#fff'}}><Icon size={17} color="var(--accent)"/><div style={{fontSize:14,fontWeight:900,marginTop:15}}>{label}</div><div className="subtitle" style={{marginTop:4}}>{meta}</div><div style={{marginTop:18,fontSize:9,color:'#6e7582'}}>OPEN MODULE <ArrowUpRight size={11} style={{verticalAlign:'middle'}}/></div></Link>)}</div></AppShell>
}
